/**
 * \mainpage
 * \section Author
 * @author Cetin Mericli
 *
 * \section Copyright
 * Version : $Id$
 *
 * \section Description
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#include <sys/types.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <semaphore.h>
#include <signal.h>
#include <sys/resource.h>

#include <albroker.h>
#include <alproxy.h>

#include <shared/ConfigFile/ConfigFile.h>
#include "NaoQiInterface.h"

static NaoQiInterface interface;
//static ConfigFile config;

static unsigned int t=0;
#ifdef __cplusplus
extern "C"
{
#endif


void preProcess()
{
    interface.act();
    //std::cout << "onpreprocess: " << std::endl;
}

void postProcess()
{
    interface.sense();
    //std::cout << "onpostprocess: " << std::endl;
}

ALCALL int _createModule( AL::ALPtr<AL::ALBroker> pBroker )
{      
    //Change it to DCM for real robot
    //AL::ALProxy* proxy = new AL::ALProxy(pBroker, "DCM");
    AL::ALProxy* proxy = new AL::ALProxy(pBroker, "ALMotion");

    interface.setBroker( pBroker );

    proxy->getModule()->atPreProcess(&preProcess);
    proxy->getModule()->atPostProcess(&postProcess);    
    
    std::cout << "CMurfs NaoQi Module has been created" << std::endl;

    return 0;
}

ALCALL int _closeModule(  )
{
  return 0;
}

# ifdef __cplusplus
}
# endif

