#ifndef VISION_CONSTANTS_DEFINED
#define VISION_CONSTANTS_DEFINED
//  #define PIXEL_FORMAT V4L2_PIX_FMT_YUYV
//  #define IMAGE_WIDTH 720
//  #define IMAGE_HEIGHT 240
  #define IMAGE_CAPTURE_INPUT 2
  #define VIDEO_DEVICE_ID 0
  #define ZERO_BOTTOM_LINES 6
#endif
